# The list of dotfile you would like linked
$dotfiles = [
  ".agignore",
  ".bash_profile",
  ".bashrc",
  "bin",
  ".ctags",
  ".gemrc",
  ".gitconfig",
  ".githelpers",
  ".gitignore_global",
  ".inputrc",
  ".irbrc",
  ".pryrc",
  ".railsrc",
  ".shell_defaults",
  ".tmux.conf",
  ".tmuxp",
  ["init.vim", ".config/nvim"],
  ["snippets", ".config/nvim"],
  ".zprofile",
  ".zshrc",
]
