#!/usr/bin/env ruby

require 'json'

# This trigger requires that you have git configured to use a commit message template located at ~/.gitmessage
# [commit]
#  template = ~/.gitmessage

message_file = ".gitmessage"
local_template_path = File.expand_path("~/#{message_file}")
spin_template_path = "/home/spin/#{message_file}"
line = "Co-Authored-By:"

# Local co-author removal
if !File.exists?(local_template_path)
  puts "No git message template found at #{local_template_path}"
else
  content = File.read(local_template_path).split("\n")
  filtered = content.reject { |l| l.include?(line) }

  File.open(local_template_path, "w") do |f|
    f.puts(filtered)
  end
end

# Spin co-author removal
spin_instances = JSON.parse(`/usr/local/bin/spin list -H -o "name,status" --json`)

spin_instances.each do |instance|
  # Only consider live spin instances
  next if instance["status"] != "available"

  commit_msg = `/usr/local/bin/spin shell #{instance["name"]} -- cat #{spin_template_path}`
  exists = !commit_msg.include?("cat: #{spin_template_path}: No such file or directory")

  # Only remove co-author line if the git message template exists and it has the co-author already
  if exists && commit_msg.include?(line)
    new_commit_msg = commit_msg.split("\n").reject do |l|
      l.include?(line)
    end.join("\n")

    `/usr/local/bin/spin shell #{instance["name"]} -- echo "'#{new_commit_msg}' > '#{spin_template_path}'"`
  end
end
