#!/usr/bin/env bash

if [[ -z "${SPIN}" ]]; then
  LOCAL_SECRETS="$HOME/.secrets"

  sed -i '' '/^export OPENAI_API_KEY=/d' $HOME/.secrets
  echo "export OPENAI_API_KEY=$1" >> $LOCAL_SECRETS
  spin secrets destroy openai-api-key
  spin secrets create openai-api-key
fi
