#!/usr/bin/env sh
#
# See https://tuple.app/triggers/docs/api-reference#call-incoming for more information on this trigger.

echo TUPLE_TRIGGER_CALLER_EMAIL $TUPLE_TRIGGER_CALLER_EMAIL
echo TUPLE_TRIGGER_CALLER_FULL_NAME $TUPLE_TRIGGER_CALLER_FULL_NAME
